---
apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    name: uat
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota
  namespace: uat
spec:
  hard:
    requests.cpu: "1" # all namespace
    requests.memory: 1Gi  # all namespace
    limits.cpu: "2"  # all namespace
    limits.memory: 2Gi  # all namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uat
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources: 
          requests: # both required
            memory: 500M
            cpu: 500m 
          limits: # both required
            memory: 500M
            cpu: 500m

