apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce # Dos pods no pueden acceder al mismo pv
  hostPath:
    path: "/test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Dos pods no pueden acceder al mismo pv
  resources:
    requests:
      storage: 10Gi # matchea línia 10