apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1" # same as 1000m
      requests:
        cpu: "0.5" # same as 500m
    args:
    - -cpus
    - "2"