apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
spec:
  containers:
    - name: test-container
      image: nginx:alpine
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName # $ k get pod podtest -o yaml
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # $ k get pod podtest -o yaml
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace # $ k get pod podtest -o yaml
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP # $ k get pod podtest -o yaml