---
apiVersion: v1
kind: Namespace
metadata:
  name: ci
  labels:
    name: ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ci
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nginx:latest

---
apiVersion: v1
kind: Service
metadata:
  namespace: ci
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  type: ClusterIP
  selector: # of the pod created
    app: backend
  ports:
    - protocol: TCP
      port: 80 # service itself port
      targetPort: 80 # container pod port